server:
  port: 8081
#  servlet:
#    context-path: "TestContext"
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  datasource:
    driver-class-name: r2dbc-postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

security:
  ignored: /**
logging:
  level:
    org:
      flyway: info
    root: info
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
